Better Startup Process

diff --git a/iptadmin b/iptadmin
--- a/iptadmin
+++ b/iptadmin
@@ -10,6 +10,9 @@ list=/etc/iptadmin.lst
 # Sets the path to the script on the client.
 scriptpath=/tmp
 
+# Static file for ipset rules to run at startup.
+ipsetrules=/etc/iptables/ipset.rules
+
 # (optional) Sets the filename for the IPTables rules/script files on the client.
 # This will allow the script to replace the iptables rules with rules that implement ipset.
 ip4rules=/etc/iptables/iptables.rules
@@ -62,16 +65,20 @@ function ipttime () { printf "$(TZ=EST5EDT date '+%H:%M:%S')"; }
 
 script=$outpath/$outfile
 
-printf '#!/bin/bash
-# Generated on '"$(date)"'
-ipset -exist create admin hash:net'"$(hosttimeout)"' family inet
-ipset -exist create admin6 hash:net'"$(hosttimeout)"' family inet6\n' > $script
+printf "#!/bin/bash
+# Generated on $(date)
+ipset -exist create admin hash:net$(hosttimeout) family inet
+ipset -exist create admin6 hash:net$(hosttimeout) family inet6
+printf 'ipset -exist create admin hash:net$(hosttimeout) family inet
+ipset -exist create admin6 hash:net$(hosttimeout) family inet6\n' | tee $ipsetrules
+" | tee $script
 
 if [ $nmsservers ]; then
  for server in $(printf $nmsservers | tr "," " "); do
   ip4address $server
   if [ $ipv4addr ]; then
-   printf 'ipset -exist add admin '"$ipv4addr$(nmstimeout)\n" >> $script
+   printf "ipset -exist add admin $ipv4addr$(nmstimeout)
+printf 'ipset -exist add admin $ipv4addr$(nmstimeout)\\\n' | tee -a $ipsetrules\n" | tee -a $script
   fi
  done
 fi
@@ -79,13 +86,15 @@ fi
 while read hostlist; do
   ip4address $hostlist
   if [ $ipv4addr ]; then
-   printf 'ipset -exist add admin '"$ipv4addr$(hosttimeout)\n" >> $script
+   printf "ipset -exist add admin $ipv4addr$(hosttimeout)
+printf 'ipset -exist add admin $ipv4addr$(hosttimeout)\\\n' | tee -a $ipsetrules\n" | tee -a $script
   fi
 done <$list
 
 if [ $ip4rules ]; then
  for port in $(echo $secureports | tr "," " "); do
-  printf "sed '/$port/c\-A INPUT -p tcp -m state --state NEW --dport $port -m set --match-set admin src -j ACCEPT' $ip4rules\n" >> $script
+  printf "sed -i '/$port/c\-A INPUT -p tcp -m state --state NEW --dport $port -m set --match-set admin src -j ACCEPT' $ip4rules\n
+" | tee -a $script
  done
 fi
 
@@ -93,7 +102,8 @@ if [ $nmsservers ]; then
  for server in $(printf $nmsservers | tr "," " "); do
   ip6address $server
   if [ $ipv6addr ]; then
-   printf 'ipset -exist add admin6 '"$ipv6addr$(nmstimeout)\n" >> $script
+   printf "ipset -exist add admin6 $ipv6addr$(nmstimeout)
+printf 'ipset -exist add admin6 $ipv6addr$(nmstimeout)\\\n' | tee -a $ipsetrules\n" | tee -a $script
   fi
  done
 fi
@@ -101,25 +111,27 @@ fi
 while read hostlist; do
   ip6address $hostlist
   if [ $ipv6addr ]; then
-   printf 'ipset -exist add admin6 '"$ipv6addr$(hosttimeout)\n" >> $script
+   printf "ipset -exist add admin6 $ipv6addr$(hosttimeout)
+printf 'ipset -exist add admin6 $ipv6addr$(hosttimeout)\\\n' | tee -a $ipsetrules\n" | tee -a $script
   fi
 done <$list
 
 if [ $ip6rules ]; then
  for port in $(echo $secureports | tr "," " "); do
-  printf "sed -i '/$port/c\-A INPUT -p tcp -m state --state NEW --dport $port -m set --match-set admin6 src -j ACCEPT' $ip6rules\n" >> $script
+  printf "sed -i '/$port/c\-A INPUT -p tcp -m state --state NEW --dport $port -m set --match-set admin6 src -j ACCEPT' $ip6rules\n
+" | tee -a $script
  done
 fi
 
-printf "if [ ! -f /etc/systemd/system/adminwhitelist.service ] || [ ! -f /etc/systemd/system/adminwhitelist.timer ]; then 
+printf "if [ ! -f /etc/systemd/system/iptwhitelistipu.service ] || [ ! -f /etc/systemd/system/iptwhitelistipu.timer ]; then
 printf '[Unit]
 Description=adminwhitelist update
 [Service]
 Type=simple
-ExecStart=/bin/sh -c '/usr/bin/curl -ks https://cpe.2l2o.net/admin.ipt > /tmp/admin.ipt && sh /tmp/admin.ipt'
+ExecStart=/bin/sh 'curl -ks $scripthost/$outfile > $scriptpath/$outfile && sh $scriptpath/$outfile'
 [Install]
 WantedBy=multi-user.target
-' | tee /etc/systemd/system/adminwhitelist.service
+' | tee /etc/systemd/system/iptwhitelistipu.service
 printf '[Unit]
 Description=adminwhitelist update scheduler
 [Timer]
@@ -127,9 +139,22 @@ OnCalendar=*:0/5
 Unit=adminwhitelist.service
 [Install]
 WantedBy=multi-user.target
-' | tee /etc/systemd/system/adminwhitelist.timer
+' | tee /etc/systemd/system/iptwhitelistipu.timer
 systemctl daemon-reload
-systemctl enable adminwhitelist.timer
+systemctl enable iptwhitelistipu.timer
+fi
+if [ ! -f /etc/systemd/system/ipset.service ]; then
+printf '[Unit]
+Description=Packet Filtering Framework
+[Service]
+Type=simple
+ExecStart=/sbin/ipset restore -f $ipsetrules
+ExecReload=/sbin/ipset restore -f $ipsetrules
+[Install]
+WantedBy=multi-user.target
+' | tee /etc/systemd/system/ipset.service
+systemctl daemon-reload
+systemctl enable ipset.service
 fi\n" >> $script
 
 if [ $failsafe == true ]; then
@@ -138,9 +163,9 @@ printf '#!/bin/bash
 ipset -exist add admin 0.0.0.0/0
 ipset -exist add admin6 ::/0\n' >> $scriptpath/awfailsafe.ipt
 fi\n" >> $script
-printf "if [ "'$(systemctl is-active awfailsafe.timer)'" != 'active' ]; then 
+printf "if [ "'$(systemctl is-active awfailsafe.timer)'" != 'active' ]; then
  systemd-run --on-active=$failtime --unit awfailsafe.service sh $scriptpath/awfailsafe.ipt
-else 
+else
  systemctl restart awfailsafe.timer
 fi\n" >> $script
 fi
